apiVersion: v1
kind: Pod
metadata:
  name: az-disk-pod
spec:
  containers:
  - name: container
    image: redis
    volumeMounts:
    - name: az-disk-pv
      mountPath: /mount1
  volumes:
  - name : az-disk-pv
    persistentVolumeClaim:
      claimName: az-disk-pvc
