apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: hostpath
      mountPath: /mount1
  volumes:
  - name : hostpath
    hostPath:
      path: /tmp
      type: Directory
