apiVersion: v1
kind: Pod
metadata:
  name: lab13-pv-pod
spec:
  containers:
  - name: container
    image: redis
    volumeMounts:
    - name: lab13-pv
      mountPath: /mount1
  volumes:
  - name : lab13-pv
    persistentVolumeClaim:
      claimName: lab13-pvc
